<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StudentApi.Application\StudentApi.Application.csproj" />
    <ProjectReference Include="..\StudentApi.Domain\StudentApi.Domain.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.20" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.79.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.20" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.20" />
  </ItemGroup>
</Project>
